name: internal_billing_khata_mobile
description: Internal billing and khata mobile app
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  drift: ^2.26.0
  flutter_secure_storage: ^9.2.2
  path: ^1.9.1
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.32

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.26.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
